"""init migration

Revision ID: 6d140e91ea96
Revises: 
Create Date: 2025-10-24 17:30:04.640295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d140e91ea96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False, comment='Автоинкрементный ID'),
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='Уникальный идентификатор кошелька'),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False, comment='Текущий баланс кошелька'),
    sa.CheckConstraint('balance >= 0', name='check_balance_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index(op.f('ix_wallets_uuid'), 'wallets', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_uuid'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
